-- MySQL Script generated by MySQL Workbench
-- Sun May 16 13:15:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ID343381_g29rummikub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ID343381_g29rummikub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ID343381_g29rummikub` DEFAULT CHARACTER SET latin1 ;
USE `ID343381_g29rummikub` ;

-- -----------------------------------------------------
-- Table `ID343381_g29rummikub`.`Speler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ID343381_g29rummikub`.`Speler` (
  `gebruikersnaam` MEDIUMTEXT NOT NULL,
  `wachtwoord` MEDIUMTEXT NOT NULL,
  `score` VARCHAR(100) NOT NULL,
  `totaalscore` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'eerste tabel';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
